"""Generate src/utils/ouiData.ts: MAC prefix -> device maker, for the Devices tab.

Source: the public IEEE OUI registry (MA-L). Only common consumer brands are kept so the
table stays small and the app never needs a network lookup (AGENTS.md §8.6).

Run: python scripts/make-oui.py            (downloads the registry)
     python scripts/make-oui.py oui.csv    (uses a local copy)
"""
import csv
import io
import sys
import urllib.request
from pathlib import Path

URL = "https://standards-oui.ieee.org/oui/oui.csv"
OUT = Path(__file__).resolve().parent.parent / "src" / "utils" / "ouiData.ts"

# Display name -> lower-case fragments of the registered organisation name.
# Order matters: the first brand that matches wins.
BRANDS: list[tuple[str, tuple[str, ...]]] = [
    ("Samsung", ("samsung",)),
    ("Apple", ("apple, inc", "apple inc")),
    ("Huawei", ("huawei",)),
    ("Honor", ("honor device",)),
    ("Xiaomi", ("xiaomi", "beijing xiaomi")),
    ("Oppo", ("guangdong oppo", "oppo mobile")),
    ("Vivo", ("vivo mobile",)),
    ("Realme", ("realme",)),
    ("OnePlus", ("oneplus",)),
    ("Motorola", ("motorola mobility",)),
    ("Nokia", ("hmd global", "nokia")),
    ("Google", ("google",)),
    ("Sony", ("sony",)),
    ("LG", ("lg electronics", "lg innotek")),
    ("TCL", ("tcl ",)),
    ("Hisense", ("hisense",)),
    ("Lenovo", ("lenovo",)),
    ("Dell", ("dell inc", "dell technologies")),
    ("HP", ("hewlett packard", "hp inc")),
    ("Asus", ("asustek",)),
    ("Acer", ("acer",)),
    ("Microsoft", ("microsoft",)),
    ("Intel", ("intel corporate",)),
    ("Realtek", ("realtek",)),
    ("MediaTek", ("mediatek",)),
    ("Qualcomm", ("qualcomm",)),
    ("Broadcom", ("broadcom",)),
    ("TP-Link", ("tp-link",)),
    ("D-Link", ("d-link",)),
    ("Tenda", ("tenda",)),
    ("Netgear", ("netgear",)),
    ("ZTE", ("zte corporation",)),
    ("Amazon", ("amazon technologies",)),
    ("Espressif", ("espressif",)),
    ("Tuya", ("tuya",)),
    ("Raspberry Pi", ("raspberry pi",)),
    ("Nintendo", ("nintendo",)),
    ("Canon", ("canon",)),
    ("Epson", ("seiko epson",)),
    ("Brother", ("brother industries",)),
    ("Hikvision", ("hikvision",)),
    ("Dahua", ("dahua",)),
    ("Infinix / Tecno", ("transsion", "infinix", "tecno")),
]


def read_registry() -> str:
    if len(sys.argv) > 1:
        return Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")
    # The registry refuses clients without a browser-like User-Agent (HTTP 418).
    agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
    request = urllib.request.Request(URL, headers={"User-Agent": agent, "Accept": "text/csv,*/*"})
    with urllib.request.urlopen(request, timeout=120) as response:
        return response.read().decode("utf-8", errors="replace")


def brand_of(organisation: str) -> str | None:
    name = organisation.lower() + " "
    for brand, fragments in BRANDS:
        if any(fragment in name for fragment in fragments):
            return brand
    return None


def main() -> None:
    by_brand: dict[str, list[str]] = {}
    for row in csv.DictReader(io.StringIO(read_registry())):
        prefix = (row.get("Assignment") or "").strip().upper()
        brand = brand_of(row.get("Organization Name") or "")
        if brand and len(prefix) == 6:
            by_brand.setdefault(brand, []).append(prefix)

    lines = [
        "// Generated by scripts/make-oui.py from the public IEEE OUI registry. Do not edit.",
        "// Brand -> its 6-hex-digit MAC prefixes, concatenated (compact; parsed once in vendor.ts).",
        "export const OUI_BY_BRAND: Record<string, string> = {",
    ]
    total = 0
    for brand, _ in BRANDS:
        prefixes = sorted(set(by_brand.get(brand, [])))
        if not prefixes:
            continue
        total += len(prefixes)
        lines.append(f"  {brand!r}: '{''.join(prefixes)}',")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{total} prefixes for {len(by_brand)} brands -> {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
